openapi: 3.0.0
info:
  version: 1.0.0
  title: TCPCM
  description: REST API for TCPCM
  license:
    name: MIT
  contact:
    name: API Support
    url: 'http://www.example.com/support'
    email: support@example.com
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /courses:
    get:
      summary: List Courses
      operationId: listCourses
      description: List courses according to the given query
      parameters:
        - name: chiefProfessor
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: An array of courses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        default:
          $ref: '#/components/responses/UnexpectedError'
    post:
      summary: Create a course
      operationId: createCourse
      description: Create a course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '201':
          $ref: '#/components/responses/NullResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'
  '/courses/{courseID}':
    get:
      summary: Course Detail
      operationId: getCourseById
      description: Information for a specific course
      parameters:
        - name: courseID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        default:
          $ref: '#/components/responses/UnexpectedError'
  /pets:
    get:
      summary: List
      operationId: listPets
      description: List all pets
      tags:
        - pets
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  tag:
                    type: string
        default:
          $ref: '#/components/responses/UnexpectedError'
    post:
      summary: Create
      operationId: createPets
      description: Create a pet
      tags:
        - pets
      responses:
        '201':
          $ref: '#/components/responses/NullResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'
  '/pets/{petId}':
    get:
      summary: Detail
      operationId: showPetById
      description: Info for a specific pet
      tags:
        - pets
      parameters:
        - $ref: '#/components/parameters/petId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/paths/~1pets/get/responses/200/content/application~1json/schema'
        default:
          $ref: '#/components/responses/UnexpectedError'
components:
  parameters:
    petId:
      name: petId
      in: path
      required: true
      description: The id of the pet to retrieve
      schema:
        type: string
    limit:
      name: limit
      in: query
      description: How many items to return at one time (max 100)
      required: false
      schema:
        type: integer
        format: int32
  schemas:
    Course:
      title: Course
      description: A TCPC Course
      type: object
      required:
        - ID
        - title
        - theme
        - chiefProfessor
      properties:
        ID:
          description: 'Unique identifier of a course,'
          type: string
        title:
          description: 'The subject title,'
          type: string
        theme:
          description: 'Course theme,'
          type: string
        chiefProfessor:
          description: The user (professor who manages this course)
          type: string
        professors:
          description: The professors teaching this course
          type: array
          items:
            type: string
        experts:
          description: The industry experts sponsoring this course
          type: array
          items:
            type: string
        students:
          description: The students taking this course
          type: array
          items:
            type: string
      example:
        ID: AF4912BFBD
        title: Capstone Project Course
        theme: Blockchain for Business Digitization
        chiefProfessor: brian
        professors:
          - brian
          - jimmy
        experts:
          - peter
          - stanley
        students:
          - alice
          - bob
    Class:
      title: Class
      description: A class under a TCPC course
      type: object
      required:
        - courseID
        - ID
        - type
        - chiefProfessor
      properties:
        courseID:
          description: The TCPC course this class is under
          type: string
        ID:
          description: Unique identifier of a class
          type: string
        type:
          description: 'The type of this class, seminar or lab'
          type: string
        componentCode:
          description: Serial number for this component starting from 1
          type: integer
          format: int32
        chiefProfessor:
          description: The professor managing this class
          type: string
        experts:
          description: The industry experts assigned to this class
          type: array
          items:
            type: string
        students:
          description: The students assigned to this class
          type: array
          items:
            type: string
    Group:
      title: Group
      description: A group in a TCPC course
      type: object
      properties:
        courseID:
          description: The TCPC course this group is under
          type: string
        ID:
          description: Unique identifier of a group
          type: string
        chiefProfessor:
          description: The professor managing this group
          type: string
        experts:
          description: The industry experts assigned to this group
          type: array
          items:
            type: string
        students:
          description: The students assigned to this group
          type: array
          items:
            type: string
    Project:
      title: Project
      description: A project in a TCPC course
      type: object
      properties:
        courseID:
          description: The TCPC course this project is under
          type: string
        ID:
          description: Unique identifier of a project
          type: string
        title:
          description: project title
          type: string
        description:
          description: a short description of this project
          type: string
        chiefProfessor:
          description: 'The professor managing this project, inherited from the course'
          type: string
        experts:
          description: 'The industry experts assigned to this project, inherited from the course'
          type: array
          items:
            type: string
        students:
          description: 'The students assigned to this project, inherited from the course'
          type: array
          items:
            type: string
    ProjectRecord:
      title: ProjectRecord
      description: A project in a TCPC course
      type: object
      properties:
        projectID:
          type: string
        groupID:
          type: string
        gradeByProfessor:
          type: string
        gradeByExpert:
          type: string
        chiefProfessor:
          type: string
        expert:
          type: string
        students:
          type: array
          items:
            type: string
    Quiz:
      title: Quiz
      description: A quiz in a TCPC course
      type: object
      properties:
        courseID:
          type: string
        ID:
          type: string
        chiefProfessor:
          type: string
        students:
          type: array
          items:
            type: string
    QuizRecord:
      title: QuizRecord
      description: Graded record for a quiz
      type: object
      properties:
        quizID:
          type: string
        grader:
          type: string
        student:
          type: string
        grade:
          type: string
    Report:
      title: Report
      description: A Report in a TCPC course
      type: object
      properties:
        courseID:
          type: string
        ID:
          type: string
        title:
          type: string
        description:
          type: string
        chiefProfessor:
          type: string
        students:
          type: array
          items:
            type: string
    ReportRecord:
      title: ReportRecord
      description: Graded and uploaded record for a report
      type: object
      properties:
        reportID:
          type: string
        sha256Checksum:
          type: string
        chiefProfessor:
          type: string
        student:
          type: string
        grade:
          type: string
  responses:
    UnexpectedError:
      description: unexpected error
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
    NullResponse:
      description: Null response
