# Ref: https://github.com/AFBlockchain/tcpcdapp/blob/main/contracts/src/main/kotlin/hk/edu/polyu/af/bc/tcpc/states/ProjectState.kt

title: Project
description: A project in a TCPC course
type: object
required:
  - courseID
  - title
  - description
properties:
  courseID:
    description: The ID of the TCPC course this project is under
    type: string
  ID:
    description: Unique identifier of a project, derived from `courseID`.
    type: string
  title:
    description: Project title
    type: string
  description:
    description: A short description of this project
    type: string
  chiefProfessor:
    description: The professor managing this project, inherited from the course
    type: string
  experts:
    description: The industry experts assigned to this project, inherited from the course
    type: array
    items:
      type: string
  students:
    description: The students assigned to this project, inherited from the course
    type: array
    items:
      type: string
example:
  courseID: AF4912BFBD
  ID: AF4912BFBD-P1
  title: Blockchain Application for Small/Medium businesses
  description: Students are expected to form a group and come up with ideas for business transformation by the Blockchain Technology.
  chiefProfessor: brian
  experts:
    - stanley
    - peter
  students:
    - alice
    - bob
    - charlie