title: Project
description: A project in a TCPC course
type: object
required:
  - courseId
  - title
  - description
properties:
  courseId:
    description: The ID of the TCPC course this project is under
    type: string
  id:
    description: Unique identifier of a project, derived from `courseID`.
    type: string
  title:
    description: Project title
    type: string
  description:
    description: A short description of this project
    type: string
example:
  courseId: AF4912BFBD
  id: AF4912BFBD-P1
  title: Blockchain Application for Small/Medium businesses
  description: Students are expected to form a group and come up with ideas for business transformation by the Blockchain Technology.
