openapi: "3.0.0"
info:
  version: 1.0.0
  title: TCPCM
  description: REST API for TCPCM
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /courses:
    $ref: ./resources/courses.yaml
  /courses/{courseID}:
    $ref: ./resources/course.yaml
  /classes:
    $ref: ./resources/classes.yaml
  /classes/{classID}:
    $ref: ./resources/class.yaml
  /quizzes:
    $ref: ./resources/quizzes.yaml
  /quizzes/{quizID}:
    $ref: ./resources/quiz.yaml
  /quiz-records/:
    $ref: ./resources/quiz-records.yaml
  /quiz-records/{quizRecordID}:
    $ref: ./resources/quiz-record.yaml
  /pets:
    $ref: "./resources/pets.yaml"
  /pets/{petId}:
    $ref: "./resources/pet.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"