openapi: "3.0.0"
info:
  version: 1.0.0
  title: TCPCM
  description: REST API for TCPCM
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://10.13.46.31:8888
paths:
  /courses:
    $ref: ./resources/course/courses.yaml
  /courses/{courseId}:
    $ref: ./resources/course/course.yaml
  /course-records/:
    $ref: ./resources/course/course-records.yaml
  /course-records/{courseRecordID}:
    $ref: ./resources/course/course-record.yaml
  /groups:
    $ref: ./resources/group/groups.yaml
  /projects:
    $ref: ./resources/project/projects.yaml
  /project-records:
    $ref: ./resources/project/project-records.yaml
  /project-records/{projectRecordID}:
    $ref: ./resources/project/project-record.yaml
  /quizzes:
    $ref: ./resources/quiz/quizzes.yaml
  /quizzes/{quizID}:
    $ref: ./resources/quiz/quiz.yaml
  /quiz-records/:
    $ref: ./resources/quiz/quiz-records.yaml
  /quiz-records/{quizRecordID}:
    $ref: ./resources/quiz/quiz-record.yaml
  /reports/:
    $ref: ./resources/report/reports.yaml
  /report-records/:
    $ref: ./resources/report/report-records.yaml
  /report-records/{reportRecordID}:
    $ref: ./resources/report/report-record.yaml
  /milestone/:
    $ref: ./resources/milestone/milestones.yaml
  /test/public:
    $ref: ./resources/test/test-public.yaml
  /test/private:
    $ref: ./resources/test/test-private.yaml
  /pets:
    $ref: "./resources/pets.yaml"
  /pets/{petId}:
    $ref: "./resources/pet.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
