name: Publish OpenAPI to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Build
        run: |
          npm ci
          npm run build
          npm run html
      - name: Deploy to GitHub Pages
        run : npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
